version: '3.8'

networks:
  default:
    external:
      name: es-network


services:

  master1:
    image: master
    container_name: master1
    networks:
      default:
        ipv4_address: 172.18.0.11

  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    privileged: true
    network_mode: service:master1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - master1

  master2:
    image: master
    container_name: master2
    networks:
      default:
        ipv4_address: 172.18.0.12
    depends_on:
      - master1

  master3:
    image: master
    container_name: master3
    networks:
      default:
        ipv4_address: 172.18.0.13
    depends_on:
      - master1


