version: '3.8'

networks:
  default:
    external:
      name: es-network

volumes:
  hostproc1:
    external: false
  hostproc2:
    external: false
  hostproc3:
    external: false
  hostsys1:
    external: false
  hostroot1:
    external: false

services:

  master1:
    build: .
    container_name: master1
    networks:
      default:
        ipv4_address: 172.18.0.11

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    privileged: true
    network_mode: service:master1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - master1

  master2:
    image: tinydfs-master-master1
    container_name: master2
    networks:
      default:
        ipv4_address: 172.18.0.12
    depends_on:
      - master1

#  cadvisor2:
#    image: google/cadvisor:latest
#    container_name: cadvisor2
#    privileged: true
#    network_mode: service:master2
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#    depends_on:
#      - master2

  master3:
    image: tinydfs-master-master1
    container_name: master3
    networks:
      default:
        ipv4_address: 172.18.0.13
    depends_on:
      - master1

#  cadvisor3:
#    image: google/cadvisor:latest
#    container_name: cadvisor3
#    privileged: true
#    network_mode: service:master3
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#    depends_on:
#      - master3
