# master 配置
master:
  addr: "127.0.0.1"
  port: ":9099"

# shadow master 配置
shadowMaster:
  addr: "127.0.0.1"
  port: ":9100"
  fsimageFlushTime: 3600    # 每隔 3600s 进行一次合并落盘

# chunk server 配置
chunk:
  waitTime: 10    # chunk server等待时间
  dieTime: 60     # chunk server死亡时间
  replicaNum: 3   # number of replica that a chunk will be store
