# master config
master:
  rpcPort: ":9099"
  raftPort: "2345"
  raftDir: "./raftData"
  cleanupTime: 86400
  directoryCheckTime: 86200
  # PanicLevel = 0
  #	FatalLevel = 1
  #	ErrorLevel = 2
  #	WarnLevel = 3
  #	InfoLevel = 4
  #	DebugLevel = 5
  #	TraceLevel = 6
  logLevel: 5

# chunk server config
chunk:
  heartbeatTime: 5
  checkTime: 60
  waitingTime: 6
#  dieTime: 600     # chunkserver died time
  dieTime: 40     # chunkserver died time
  replicaNum: 3   # number of replica that a chunk will be store
#  deadChunkCheckTime: 180  # dead chunk will be copied every 180s
  deadChunkCheckTime: 60  # dead chunk will be copied every 180s
  deadChunkCopyThreshold: 32  # dead chunk will be copied when count is 32 or more
  directoryCheckTime: 12
  storableCheckTime: 60
  storableThreshold: 80
  expandThreshold : 10

# etcd config
etcd:
  endPoint: "172.18.0.20:2379"

# metrics config
metrics:
  port: "9101"
