# master 配置
master:
  rpcPort: ":9099"
  raftPort: "2345"
  raftDir: "./raftData"

# chunk server 配置
chunk:
  checkTime: 180
  dieTime: 600     # chunk server死亡时间
  replicaNum: 3   # number of replica that a chunk will be store

# etcd config
etcd:
  endPoint: "172.18.0.20:2379"
