# master config
master:
  rpcPort: ":9099"
  raftPort: "2345"
  raftDir: "./raftData"

# chunk server config
chunk:
  checkTime: 180
  dieTime: 600     # chunkserver died time
  replicaNum: 3   # number of replica that a chunk will be store

# etcd config
etcd:
  endPoint: "172.18.0.20:2379"

# metrics config
metrics:
  port: "9101"
